### ISSUE TITLE
I think this should be a integer and considered as enum

### ISSUE THREAD

**Issue by SuzukiRyuichiro** [SarahKatherineFrancis/journo#5]
https://github.com/SarahKatherineFrancis/journo/blob/6e756ec8dfa856f19cf33720bbca306eeab37584/db/schema.rb#L21

**Comment by SuzukiRyuichiro** [comment]
I.e. 
```
0 => not_added
1 => considering
2 => added
```

**Comment by SarahKatherineFrancis** [comment]
Thanks @SuzukiRyuichiro, I have changed it to an integer
