### ISSUE TITLE
Will there be only one food preferences?

### ISSUE THREAD

**Issue by SuzukiRyuichiro** [SarahKatherineFrancis/journo#6]
https://github.com/SarahKatherineFrancis/journo/blob/6e756ec8dfa856f19cf33720bbca306eeab37584/db/schema.rb#L51

I thought we can have multiple food preferences such as
- Lactose intorence
- Gluten free
- Vegan
- Vegetarian
- Local
- Organic

And stuff like that. And perhaps let the user choose multiple of them when creating a new trip

For that, having just one column to represent multiple selection is not sufficient. I forgot if I mentioned but we can let the users type or check multiple of them and save them using a gem called [acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on)

**Comment by SarahKatherineFrancis** [comment]
This is great. Thanks @SuzukiRyuichiro

**Comment by SuzukiRyuichiro** [comment]
So maybe Trip model can have 
```
acts_as_taggable_on :food_preferences
```
and when sending a request to ChatGPT or just straight to Google Maps API, you can join the food preferences tags or whatever to make it into a single string

**Comment by SuzukiRyuichiro** [comment]
Also something like tom select might be a nice UI to add food preferences https://tom-select.js.org/examples/
